services:
  - type: web
    name: synergeticspark-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: LEAD_RECEIVER_EMAIL
        sync: false
